### PR TITLE
Symfony 4 support

### PR DESCRIPTION
**Pull request by bodorszilard**
#SymfonyConHackday2017

### CODE REVIEW

**Comment by bodorszilard** [comment]
@alcaeus Done

**Comment by alcaeus** [comment]
Test failures still look unrelated, but dev build tests Symfony 3.4 probably due to version constraints in other dependencies.

**Comment by bodorszilard** [comment]
okay, thanks @alcaeus

**Comment by bravik** [comment]
In addition "jms_i18n_routing.loader" should be declared as public
in JMSI18nRoutingBundle/Resources/config/services.xml:
<service id="jms_i18n_routing.loader" class="%jms_i18n_routing.loader.class%" public="true">
otherwise there is an error from this issue:
[issue215](https://github.com/schmittjoh/JMSI18nRoutingBundle/issues/215)

**Comment by acasademont** [comment]
SF4 is now supported, thx!

**Pull request closed without merging**
