### PR TITLE
Translation logging fix

### LINKED ISSUE #141: problem with Symfony 2.6.x
please see the description here:
https://github.com/symfony/symfony/issues/12941#issuecomment-66872843

### PR DESCRIPTION
**Pull request by cmfcmf**
[Only look at the second commit to see the actual changes.](https://github.com/schmittjoh/JMSI18nRoutingBundle/pull/144/files?w=1)

This resolves #141. It does an extra check for the LoggingTranslator, because it didn't implement the TranslatorBagInterface until Symfony version 2.6.5 (see https://github.com/symfony/symfony/issues/13632).

### CODE REVIEW

**Comment by craigh** [comment]
ping @schmittjoh

**Comment by ecentinela** [comment]
ping @schmittjoh

**Comment by schmittjoh** [comment]
Before merging, could you have a look at the line endings, it seems like something went wrong there?

**Comment by cmfcmf** [comment]
They were wrong in the original file, which I fixed in https://github.com/cmfcmf/JMSI18nRoutingBundle/commit/ba8be27e582236835df03cce7052a140bf5922a8.

**Comment by craigh** [comment]
@schmittjoh is there still a concern?

**Comment by stof** [comment]
@cmfcmf can you submit the line-ending change separately, so that it can be merged first (meaning that after rebasing, this PR will have a meaningful diff which can be revewed)

**Comment by schmittjoh** [comment]
@stof, btw, you can add ``?w=1`` to get rid of the whitespace changes.

**Comment by craigh** [comment]
thank you for merging. do you intent another tagged release anytime soon?

**Pull request merged**
