### PR TITLE
The `router` alias is public

### LINKED ISSUE #216: User Deprecated: The "router" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0
I got the following deprecation after updating to Symfony 3.4:

> User Deprecated: The "router" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

Error:

> "exception" => ErrorException {#2303 ▼
    #message: "User Deprecated: The "router" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead."
    #code: 0
    #file: "vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php"
    #line: 275
    #severity: E_USER_DEPRECATED
    trace: {▼
      vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:275 {▶}
      vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php:85 {▶}
      src/AppBundle/Controller/Backend/DashboardController.php:16 {▼
        ›     ->setPageTitle('Dashboard')
        ›     ->addBreadcrumb('Dashboard', $this->generateUrl('backend.dashboard'), 'dashboard')
        › ;
      }
      AppBundle\Controller\Backend\DashboardController->indexAction() {}
      vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153 {▶}
      vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68 {▶}
     vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202 {▶}
      web/app_dev.php:33 {▶}
    }
  }

I first filed it here: https://github.com/symfony/symfony/issues/25328
But there we realized that the problem has to be with JMSI18nRoutingBundle as disabling the bundle solved the problem.

This is also related to: https://github.com/schmittjoh/JMSI18nRoutingBundle/issues/215

### PR DESCRIPTION
**Pull request by sroze**
This is fix #216

### CODE REVIEW

**Comment by acasademont** [comment]
Thx @sroze!

**Comment by raphaChoquet** [comment]
For information, this fix isn't compatible with Symfony 2 and 3 because setAlias return null, therefore you can't set public at true.  
You have to use the method getAlias to retrieve it and then set public at true.

```
$container->setAlias('router', 'jms_i18n_routing.router');    
$container->getAlias('router')->setPublic(true);
```

**Comment by acasademont** [comment]
@raphaChoquet noticed it this morning, the fix is already commited and tagged :=)

**Comment by sroze** [comment]
Great, thanks for sorting it. Sorry for the BC.

**Comment by raphaChoquet** [comment]
Ok thx!  :)  i can update my repo then !

**Comment by acasademont** [comment]
yep, sorry for that, having so many different SF versions to test on is a PITA sometimes :p

**Comment by raphaChoquet** [comment]
Yes i understand, thx for have it done rapid!

**Pull request merged**
