### PR TITLE
Update I18nRouter.php

### PR DESCRIPTION
**Pull request by vytsci**
This line causes compile error on Symfony 4.2.x

### CODE REVIEW

**Comment by esserj** [comment]
Could this please be a fast out-of-cycle hotfix as out CI pipelines are failing and we would have to release 2 hotfixes for our packages, one with the ignore and one with it removed again! thanks!

**Comment by DavidVerdier** [comment]
Please merge this

**Comment by acasademont** [comment]
merged thanks, cutting a release asap

**Comment by acasademont** [comment]
Just tagged 3.0.3, let me know if things are working fine again.

**Comment by esserj** [comment]
@acasademont worked for us, thank you!

**Pull request merged**
